/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-24 16:07:04
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "tcp.h"

#include "tcp.h"
static void kleva_stub_TcpRecvHandler(Tcb *tcb, Packet *payload, void *ctx) {
    (void)tcb;
    (void)payload;
    (void)ctx;
}
static void kleva_stub_TcpConnectHandler(Tcb *tcb, void *ctx) {
    (void)tcb;
    (void)ctx;
}

static void test_init_null_tv001(void) {
    tcp_init(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_null_tv001\n");
}

static void test_init_valid_tv001(void) {
    TcpTable table;
    memset(&table, 0, sizeof(table));
    tcp_init(&table);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_valid_tv001\n");
}

static void test_listen_null_input_tv001(void) {
    Tcb * out_ret = tcp_listen(NULL, 0, 0, NULL, NULL, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_listen_null_input_tv001\n");
}

static void test_listen_duplicate_tv001(void) {
    TcpTable table;
    memset(&table, 0, sizeof(table));
    table.tcbs[0].valid = 1;
    table.tcbs[0].state = TCP_LISTEN;
    table.tcbs[0].local_ip = 0;
    table.tcbs[0].local_port = 1;
    Tcb * out_ret = tcp_listen(&table, 0, 1, kleva_stub_TcpRecvHandler, kleva_stub_TcpConnectHandler, NULL);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_local_ip = out_ret ? out_ret->local_ip : 0;
    uint16_t out_local_port = out_ret ? out_ret->local_port : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_local_ip == 0); /* EVA-proven oracle */
    assert(out_local_port == 0); /* EVA-proven oracle */
    printf("PASS test_listen_duplicate_tv001\n");
}

static void test_listen_valid_tv001(void) {
    TcpTable table;
    memset(&table, 0, sizeof(table));
    Tcb * out_ret = tcp_listen(&table, 0, 1, kleva_stub_TcpRecvHandler, kleva_stub_TcpConnectHandler, NULL);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_local_ip = out_ret ? out_ret->local_ip : 0;
    uint16_t out_local_port = out_ret ? out_ret->local_port : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_local_ip == 0); /* EVA-proven oracle */
    assert(out_local_port == 1); /* EVA-proven oracle */
    printf("PASS test_listen_valid_tv001\n");
}

static void test_connect_null_input_tv001(void) {
    Tcb * out_ret = tcp_connect(NULL, NULL, 0, 0, 0, 0, NULL, NULL, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_connect_null_input_tv001\n");
}

static void test_connect_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    TcpTable table;
    memset(&table, 0, sizeof(table));
    Tcb * out_ret = tcp_connect(sim, &table, 1, 1, 1, 1, kleva_stub_TcpRecvHandler, kleva_stub_TcpConnectHandler, NULL);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_local_ip = out_ret ? out_ret->local_ip : 0;
    uint32_t out_remote_ip = out_ret ? out_ret->remote_ip : 0;
    uint16_t out_local_port = out_ret ? out_ret->local_port : 0;
    uint16_t out_remote_port = out_ret ? out_ret->remote_port : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_local_ip == 0); /* EVA-proven oracle */
    assert(out_remote_ip == 0); /* EVA-proven oracle */
    assert(out_local_port == 0); /* EVA-proven oracle */
    assert(out_remote_port == 0); /* EVA-proven oracle */
    printf("PASS test_connect_valid_tv001\n");
}

static void test_send_null_input_tv001(void) {
    int out_ret = tcp_send(NULL, NULL, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_null_input_tv001\n");
}

static void test_send_invalid_tcb_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    Tcb tcb;
    memset(&tcb, 0, sizeof(tcb));
    int out_ret = tcp_send(sim, &tcb, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_invalid_tcb_tv001\n");
}

static void test_send_empty_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    Tcb tcb;
    memset(&tcb, 0, sizeof(tcb));
    uint8_t data_buf[64];
    memset(data_buf, 0, sizeof(data_buf));
    tcb.valid = 1;
    tcb.state = TCP_ESTABLISHED;
    int out_ret = tcp_send(sim, &tcb, data_buf, 0);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_empty_tv001\n");
}

static void test_send_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    Tcb tcb;
    memset(&tcb, 0, sizeof(tcb));
    uint8_t data_buf[64];
    memset(data_buf, 0, sizeof(data_buf));
    tcb.valid = 1;
    tcb.state = TCP_ESTABLISHED;
    int out_ret = tcp_send(sim, &tcb, data_buf, 1);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_send_valid_tv001\n");
}

static void test_receive_null_iface_tv001(void) {
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    int out_ret = tcp_receive(NULL, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_receive_null_iface_tv001\n");
}

static void test_receive_null_pkt_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    int out_ret = tcp_receive(iface, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_pkt_tv001\n");
}

static void test_receive_null_ctx_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    int out_ret = tcp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_ctx_tv001\n");
}

static void test_receive_bad_ctx_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    int out_ret = tcp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_bad_ctx_tv001\n");
}

static void test_receive_too_short_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = ((20) > 0 ? (20) - 1 : 0);
    int out_ret = tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_too_short_tv001\n");
}

static void test_receive_readable_tcp_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    int out_ret = tcp_receive(iface, pkt, &ctx_TcpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_readable_tcp_tv001\n");
}

static void test_receive_source_local_ip_tmp_0_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_local_ip_tmp_0_tv001\n");
}

static void test_receive_source_local_ip_not_tmp_0_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_local_ip_not_tmp_0_tv001\n");
}

static void test_receive_source_tcb_state_TCP_SYN_SENT_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_SYN_SENT;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_SYN_SENT_tv001\n");
}

static void test_receive_source_tcb_state_TCP_SYN_RECEIVED_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_SYN_RECEIVED;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_SYN_RECEIVED_tv001\n");
}

static void test_receive_source_tcb_state_TCP_ESTABLISHED_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_ESTABLISHED;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_ESTABLISHED_tv001\n");
}

static void test_receive_source_tcb_state_TCP_FIN_WAIT_1_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_FIN_WAIT_1;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_FIN_WAIT_1_tv001\n");
}

static void test_receive_source_tcb_state_TCP_FIN_WAIT_2_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_FIN_WAIT_2;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_FIN_WAIT_2_tv001\n");
}

static void test_receive_source_tcb_state_TCP_CLOSING_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_CLOSING;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_CLOSING_tv001\n");
}

static void test_receive_source_tcb_state_TCP_LAST_ACK_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_LAST_ACK;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_LAST_ACK_tv001\n");
}

static void test_receive_source_tcb_state_TCP_TIME_WAIT_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    pkt->len = 20;
    pkt->data = pkt->head + 20;
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(0);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_TCP;
    Simulator kleva_tcp_ctx_sim_guard;
    memset(&kleva_tcp_ctx_sim_guard, 0, sizeof(kleva_tcp_ctx_sim_guard));
    ((TcpContext *)&ctx_TcpContext)->sim = &kleva_tcp_ctx_sim_guard;
    TcpTable kleva_tcb_tcbs_owner;
    memset(&kleva_tcb_tcbs_owner, 0, sizeof(kleva_tcb_tcbs_owner));
    ((TcpContext *)&ctx_TcpContext)->table = &kleva_tcb_tcbs_owner;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->dst_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].local_port = 1;
    ((TcpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_ip = 1;
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->src_ip = ns_htonl(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].remote_port = 1;
    ((TcpHeader *)pkt->data)->src_port = ns_htons(1);
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].valid = 1;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = 0;
    ((TcpContext *)&ctx_TcpContext)->table->tcbs[0].state = TCP_TIME_WAIT;
    tcp_receive(iface, pkt, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_tcb_state_TCP_TIME_WAIT_tv001\n");
}

static void test_close_null_input_tv001(void) {
    int out_ret = tcp_close(NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_close_null_input_tv001\n");
}

static void test_close_invalid_tcb_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    Tcb tcb;
    memset(&tcb, 0, sizeof(tcb));
    tcb.valid = 0;
    int out_ret = tcp_close(sim, &tcb);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_close_invalid_tcb_tv001\n");
}

static void test_close_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    Tcb tcb;
    memset(&tcb, 0, sizeof(tcb));
    tcb.valid = 1;
    int out_ret = tcp_close(sim, &tcb);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_close_valid_tv001\n");
}

static void test_retransmit_handler_null_event_tv001(void) {
    tcp_retransmit_handler(NULL, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_retransmit_handler_null_event_tv001\n");
}

static void test_retransmit_handler_null_ctx_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    tcp_retransmit_handler(e, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_retransmit_handler_null_ctx_tv001\n");
}

static void test_retransmit_handler_bad_ctx_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    tcp_retransmit_handler(e, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_retransmit_handler_bad_ctx_tv001\n");
}

static void test_retransmit_handler_valid_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    tcp_retransmit_handler(e, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_retransmit_handler_valid_tv001\n");
}

static void test_retransmit_handler_source_tcb_valid_eq_1_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    Tcb kleva_tcb_data_storage;
    memset(&kleva_tcb_data_storage, 0, sizeof(kleva_tcb_data_storage));
    e->data = &kleva_tcb_data_storage;
    ((Tcb *)e->data)->valid = 1;
    tcp_retransmit_handler(e, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_retransmit_handler_source_tcb_valid_eq_1_tv001\n");
}

static void test_retransmit_handler_source_tcb_valid_ne_1_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    TcpContext ctx_TcpContext;
    memset(&ctx_TcpContext, 0, sizeof(ctx_TcpContext));
    Tcb kleva_tcb_data_storage;
    memset(&kleva_tcb_data_storage, 0, sizeof(kleva_tcb_data_storage));
    e->data = &kleva_tcb_data_storage;
    ((Tcb *)e->data)->valid = 0;
    tcp_retransmit_handler(e, &ctx_TcpContext);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_retransmit_handler_source_tcb_valid_ne_1_tv001\n");
}

int main(void) {
    test_init_null_tv001();
    test_init_valid_tv001();
    test_listen_null_input_tv001();
    test_listen_duplicate_tv001();
    test_listen_valid_tv001();
    test_connect_null_input_tv001();
    test_connect_valid_tv001();
    test_send_null_input_tv001();
    test_send_invalid_tcb_tv001();
    test_send_empty_tv001();
    test_send_valid_tv001();
    test_receive_null_iface_tv001();
    test_receive_null_pkt_tv001();
    test_receive_null_ctx_tv001();
    test_receive_bad_ctx_tv001();
    test_receive_too_short_tv001();
    test_receive_readable_tcp_tv001();
    test_receive_source_local_ip_tmp_0_tv001();
    test_receive_source_local_ip_not_tmp_0_tv001();
    test_receive_source_tcb_state_TCP_SYN_SENT_tv001();
    test_receive_source_tcb_state_TCP_SYN_RECEIVED_tv001();
    test_receive_source_tcb_state_TCP_ESTABLISHED_tv001();
    test_receive_source_tcb_state_TCP_FIN_WAIT_1_tv001();
    test_receive_source_tcb_state_TCP_FIN_WAIT_2_tv001();
    test_receive_source_tcb_state_TCP_CLOSING_tv001();
    test_receive_source_tcb_state_TCP_LAST_ACK_tv001();
    test_receive_source_tcb_state_TCP_TIME_WAIT_tv001();
    test_close_null_input_tv001();
    test_close_invalid_tcb_tv001();
    test_close_valid_tv001();
    test_retransmit_handler_null_event_tv001();
    test_retransmit_handler_null_ctx_tv001();
    test_retransmit_handler_bad_ctx_tv001();
    test_retransmit_handler_valid_tv001();
    test_retransmit_handler_source_tcb_valid_eq_1_tv001();
    test_retransmit_handler_source_tcb_valid_ne_1_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
